"""initial schema

Revision ID: d7353c302ac7
Revises: None
Create Date: 2026-07-06 04:07:02.330336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7353c302ac7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pipeline_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_key', sa.String(length=64), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_key')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_count >= 0', name='chk_failed_count_non_neg'),
    sa.CheckConstraint('skipped_count >= 0', name='chk_skipped_count_non_neg'),
    sa.CheckConstraint('success_count >= 0', name='chk_success_count_non_neg'),
    sa.CheckConstraint('total_products >= 0', name='chk_total_products_non_neg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=150), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('search_query_used', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(display_name) > 0', name='chk_display_name_not_empty'),
    sa.CheckConstraint('price_usd >= 0', name='chk_price_positive'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'model_name', 'category_id', 'gender', 'color', 'material', name='uq_sneakers_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sneakers')
    op.drop_table('pipeline_runs')
    op.drop_table('pipeline_cache')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
